name: Test
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        nimVersion:
          - stable
          - 1.6.20
        nimMm:
          - orc
          - arc
          - refc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nimVersion }}
      - run: nimble test -Y --mm:${{ matrix.nimMm }}
